---
label: Project
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: link
  label: Link
  type: textarea
  hidden: false
  default: ''
