---
label: Project
hide_body: true
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
  description: Name of the external project
- name: link
  label: Link
  type: textarea
  hidden: false
  default: ''
  description: 'URL for external project '
